export const topSearched = {
    'United Kingdom': 0,
    'Spain': 1,
    'Italy': 2,
    'France': 3,
    'Germany': 4,
    'Greece': 5,
    'Austria': 6,
    'Croatia': 7,
    'Netherlands': 8,
    'Portugal': 9,
    'Sweden': 10,
    'Poland': 11,
    'Czech Republic': 12,
    'Denmark': 13,
    'Romania': 14,
    'Belgium': 15,
    'Hungary': 16,
    'Bulgaria': 17,
    'Ireland': 18,
    'Slovakia': 19,
    'Finland': 20,
    'Estonia': 21,
    'Malta': 22,
    'Cyprus': 23,
    'Slovenia': 24,
    'Latvia': 25,
    'Lithuania': 26,
    'Luxembourg': 27,
};